version: '3'

services:
  redis:
    container_name: app-redis-db
    image: redis:6.2.10-alpine
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - ./redis_data:/data
    ports:
      - "6378:6379"
    networks:
      - nginxnet

  fastapi-app:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --proxy-headers
    volumes:
      - ./app:/app
    depends_on:
      - redis
    networks:
      - nginxnet
    deploy:
      replicas: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8100:8000"
    depends_on:
      - fastapi-app
    networks:
      - nginxnet

networks:
  nginxnet: